### GET All users
GET http://localhost:2200/users
Content-Type: application/json


### GET All tweets by user
GET http://localhost:2200/users/1/tweets
Content-Type: application/json



### GET a user roles
GET http://localhost:2200/users/roles/1
Content-Type: application/json

### Create a user
POST http://localhost:2200/users
Content-Type: application/json

{
  "firstName": "alex2",
  "lastName": "mia",
  "email": "alex2@gmail.com"
}

### GET All tweets
GET http://localhost:2200/tweets
Content-Type: application/json

### Create a tweets
POST http://localhost:2200/tweets
Content-Type: application/json

{
  "title": "Rust New Things",
  "content": "text content",
  "authorId": "3",
  "cover": "http://photo.jpg"
}


### GET a tweet
GET http://localhost:2200/tweets/1
Content-Type: application/json


### GET a tweet detail
GET http://localhost:2200/tweets/detail/1
Content-Type: application/json


### Create a tweet like
POST http://localhost:2200/tweets/like
Content-Type: application/json

{
  "tweetId": "1",
  "userId": "4"
}


### Create a tweet comment
POST http://localhost:2200/tweets/comment
Content-Type: application/json

{
  "content": "Super post",
  "tweetId": "1",
  "authorId": "4"
}




### Find a Products
GET http://localhost:2200/products
Content-Type: application/json


### Find user Products
GET http://localhost:2200/products/users/4
Content-Type: application/json


### Create a Product
POST http://localhost:2200/products
Content-Type: application/json

{
  "title": "Macbook pro m2",
  "price": 3000.99,
  "authorId": "4"
}




### Get all Categories
GET http://localhost:2200/categories
Content-Type: application/json

### Get all Categories with nested
GET http://localhost:2200/categories/nested
Content-Type: application/json

### Get all Categories with all parent
GET http://localhost:2200/categories/parent
Content-Type: application/json


### Create a Product
POST http://localhost:2200/categories
Content-Type: application/json

{
  "name": "Earphone",
  "slug": "Earphone",
  "parentId": 13
}




###